### ISSUE TITLE
npm shim higher in PATH than resolved executable

### ISSUE THREAD

**Issue by craigfurman** [asdf-community/asdf-direnv#82]
With a `.tool-versions` file containing:

```
nodejs 14.16.1
```

And a `.envrc` containing:

```
use asdf
```

After upgrading `npm` with `npm install -g npm` (although this problem also appears to manifest itself when using the node-bundled npm), `which -a npm` on my system returns:

```
/Users/craig/.asdf/plugins/nodejs/shims/npm
/Users/craig/.asdf/installs/nodejs/14.16.1/.npm/bin/npm
/Users/craig/.asdf/installs/nodejs/14.16.1/bin/npm
/Users/craig/.asdf/shims/npm
```

An asdf npm shim, `$ASDF_HOME/plugins/nodejs/shims/npm`, is higher up my path than the asdf-resolved npm executable script, `$ASDF_HOME/installs/nodejs/14.16.1/.npm/bin/npm`.

Apologies if this issue is in the wrong place, it's possible I'm misunderstanding how the asdf toolchain including the nodejs plugin is supposed to work.

If I understand correctly, the generated `PATH_add` directives in the generated direnv file cause PATH to be prepended, and are in reverse order to how they should be to avoid the shim:

```
log_status using asdf nodejs 14.16.1
export NPM_CONFIG_PREFIX=$'/Users/craig/.asdf/installs/nodejs/14.16.1/.npm'
PATH_add /Users/craig/.asdf/installs/nodejs/14.16.1/bin
PATH_add /Users/craig/.asdf/installs/nodejs/14.16.1/.npm/bin
PATH_add /Users/craig/.asdf/plugins/nodejs/shims 
```

**Comment by smorimoto** [comment]
Have you tried updating asdf-nodejs to the latest version?

**Comment by craigfurman** [comment]
Yeah, I was already on the latest version as of today

**Comment by smorimoto** [comment]
See https://github.com/asdf-vm/asdf-nodejs/pull/212.

**Comment by craigfurman** [comment]
Hmm I see, so it sounds like it should already be fixed? I'm already running a plugin version that contains that merged PR though

**Comment by smorimoto** [comment]
If the setup is fine, it should be fixed with the PR.

**Comment by craigfurman** [comment]
Have you tried to reproduce this? It occurs even after that PR

**Comment by craigfurman** [comment]
@smorimoto I looked into this a little bit, and it looks like https://github.com/asdf-vm/asdf-nodejs/pull/232 might have introduced a similar PATH ordering problem for asdf-direnv to the one you solved in https://github.com/asdf-vm/asdf-nodejs/pull/212. Not 100% sure yet

**Comment by jfly** [comment]
I dug into this a bit, and this definitely is still happening. For example, on my laptop with the latest versions of `asdf`, `asdf-direnv`, and `asdf-nodejs`:

```
$ cat .tool-versions
nodejs 14.17.5
$ which -a npm
/home/jeremy/.asdf/plugins/nodejs/shims/npm
/home/jeremy/.asdf/installs/nodejs/14.17.5/.npm/bin/npm
/home/jeremy/.asdf/installs/nodejs/14.17.5/bin/npm
```

@craigfurman I think you're correct that this `.../shims/npm` is showing up because of https://github.com/asdf-vm/asdf-nodejs/pull/232/. This ultimately boils down to this line of code in `asdf`: https://github.com/asdf-vm/asdf/blob/v0.9.0/lib/utils.bash#L517-L521, which comes before this line: https://github.com/asdf-vm/asdf/blob/v0.9.0/lib/utils.bash#L529-L531.

Also worth noting: I'm not too familiar with this type of shim, it's not a normal asdf shim, I think it's a ["Custom Shim Template"](https://asdf-vm.com/plugins/create.html#custom-shim-templates). As far as I can tell, it looks like this shim *is* correctly delegating to the right version of npm, so I don't think there's actually anything going wrong for me. In the same order as `which -a npm`:
```
$ /home/jeremy/.asdf/plugins/nodejs/shims/npm --version
8.5.3
$ /home/jeremy/.asdf/installs/nodejs/14.17.5/.npm/bin/npm --version
8.5.3
$ /home/jeremy/.asdf/installs/nodejs/14.17.5/bin/npm --version
6.14.14
```

Still, I feel like one of the benefits of using `asdf-direnv` is that you don't have to think about the indirection of shims ([most of our README](https://github.com/asdf-community/asdf-direnv/#motivation-or-shims-de-motivation) is about the benefits of that!), and it's not like we need the auto re-shimming that this npm wrapper exists to do.

I just don't know enough about asdf to even guess about how to fix this. The only (bad) idea I have would be for us to filter out folders that have "shims" in them, which would one heck of hack. Perhaps @vic or @smorimoto have some idea about something we could do?

**Comment by comfortablynick** [comment]
I noticed this issue today too. Everything may still _work_ but we lost the benefits of asdf-direnv it would seem.

**Comment by vic** [comment]
Looking at our source code, it looks like in order to obtain the plugin's environment variables, we use asdf's [with_plugin_env](https://github.com/asdf-community/asdf-direnv/blob/master/lib/commands/command.bash#L217). And that ultimately calls [`list_plugin_exec_paths`](https://github.com/asdf-vm/asdf/blob/2a538fe63144c3d0710df23738c1f06363b10fa6/lib/utils.bash#L518) which *does includes the `<plugin>/shims/` directory*, even when the asdf [documentation](https://asdf-vm.com/plugins/create.html#custom-shim-templates) says that custom shims get _copied_ to the `asdf/shims` directory, and thus there would be no need for `<plugin>/shims` to be part of PATH. 

One thing we could do on our end is not to use `with_plugin_env` but instead [`list_plugin_exec_paths`](https://github.com/asdf-vm/asdf/blob/2a538fe63144c3d0710df23738c1f06363b10fa6/lib/utils.bash#L559) and append them to PATH and [`exec-env`](https://github.com/asdf-vm/asdf/blob/2a538fe63144c3d0710df23738c1f06363b10fa6/lib/utils.bash#L566) for other plugin related env-variables.

**Comment by jfly** [comment]
> but instead [list_plugin_exec_paths](https://github.com/asdf-vm/asdf/blob/2a538fe63144c3d0710df23738c1f06363b10fa6/lib/utils.bash#L559) and append them to PATH

But won't `list_plugin_exec_paths` include these `<plugin>/shims/` because of this block of code: https://github.com/asdf-vm/asdf/blob/2a538fe63144c3d0710df23738c1f06363b10fa6/lib/utils.bash#L517-L521?

> even when the asdf [documentation](https://asdf-vm.com/plugins/create.html#custom-shim-templates) says that custom shims get copied to the asdf/shims directory, and thus there would be no need for <plugin>/shims to be part of PATH.

Are you saying this might be an asdf bug that we could try to fix? That feels cleaner to me than trying to work around it down here.

**Comment by vic** [comment]
> But won't `list_plugin_exec_paths` include these `<plugin>/shims/` because of this block of code: [asdf-vm/asdf@`2a538fe`/lib/utils.bash#L517-L521](https://github.com/asdf-vm/asdf/blob/2a538fe63144c3d0710df23738c1f06363b10fa6/lib/utils.bash#L517-L521)?

You are right,  I was thinking of `list_plugin_bin_paths` instead. which calls [`<plugin>/list-bin-paths`](https://github.com/asdf-vm/asdf-nodejs/pull/212/files#diff-be1029d61c2cef5289db0110a35ed928ec548ee1557bc35c95e2132acf4f73abR3). 

Anyways, perhaps a simpler solution for us is to just ignore `<plugin>/shims` paths as you previously suggested.

Since asdf's custom-shims seem to be a workaround some shims themselves, I don't really know if _fixing_ this in asdf will lead to some other bugs in many existing plugins (since those custom shims are not being copied as stated in the docs, but just added to PATH).

**Comment by vic** [comment]
I've made an experimental PR to fix this: #109, could anybody confirm it works as expected?
